version: "3.1"
services:
    postgres: 
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: actix
            POSTGRES_USER: actix
            POSTGRES_DB: granules
        ports:
            - 8081:5432


